name: Update contribution graphs

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Build graphs
        run: |
          python src/generate_pr_heatmap.py --out assets/pr_heatmap.svg
          python src/generate_annual_contribs.py --out assets/annual_contribs.svg
      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: auto-update contribution graphs"
          file_pattern: |
            assets/pr_heatmap.svg
            assets/annual_contribs.svg
