name: Update PR heat-map

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  heatmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate heat-map
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/generate_contrib_heatmap.py
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: 'assets/pr_heatmap.svg'
          message: 'docs: update PR contribution heat-map [skip ci]'
