name: Rebuild 3-D heat-map

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  heatmap:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          uv pip install --system -r requirements.txt
      - name: Generate heat-map
        if: env.GH_TOKEN != ''
        run: python src/generate_heatmap.py
      - name: Commit and push
        if: env.GH_TOKEN != ''
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: 'assets/heatmap_*.svg'
          message: 'docs: auto-update 3-D LOC heat-map [skip ci]'
      - name: Skip heat-map build
        if: env.GH_TOKEN == ''
        run: echo 'GH_TOKEN not set, skipping heat-map'

